"use client";
/* eslint-disable jsx-a11y/media-has-caption, jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions, jsx-a11y/label-has-associated-control -- studio visuel : contrôles imbriqués compactés et capture brute du propriétaire */

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { createTwinAutomation, createTwinRenderJob, removeTwinAutomation, saveTwinProfile, toggleTwinAutomation, uploadTwinAsset, watchTwinAutomations, watchTwinProfile, type TwinAutomation, type TwinGesture, type TwinProfile, type TwinSequenceStep } from "@/lib/whappy-twin";

type Tab="engine"|"capture"|"voice"|"automation"|"produce";
const gestures:{id:TwinGesture;label:string;icon:string;description:string}[]=[
  {id:"neutral",label:"Présence",icon:"◎",description:"Posture calme et regard caméra"},{id:"welcome",label:"Accueil",icon:"◡",description:"Ouverture des bras et sourire"},{id:"explain",label:"Expliquer",icon:"≋",description:"Gestes pédagogiques naturels"},{id:"point",label:"Pointer",icon:"↗",description:"Dirige l’attention vers un détail"},{id:"show",label:"Présenter",icon:"◇",description:"Mise en valeur d’un produit"},{id:"wave",label:"Saluer",icon:"⌁",description:"Salut énergique de la main"},{id:"walk",label:"Mouvement",icon:"⌁",description:"Déplacement latéral fluide"},
];
const baseSequence:TwinSequenceStep[]=[{gesture:"welcome",duration:2,label:"Ouverture"},{gesture:"show",duration:4,label:"Produit"},{gesture:"explain",duration:5,label:"Argumentaire"},{gesture:"point",duration:2,label:"Appel à l’action"}];
function clock(seconds:number){return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;}

export function TwinEngineStudio({userId,userName,consent,setConsent,notify}:{userId:string;userName:string;consent:boolean;setConsent:(value:boolean)=>void;notify:(text:string)=>void}){
  const [tab,setTab]=useState<Tab>("engine");const [profile,setProfile]=useState<TwinProfile|null>(null);const [automations,setAutomations]=useState<TwinAutomation[]>([]);const [gesture,setGesture]=useState<TwinGesture>("welcome");const [intensity,setIntensity]=useState(72);const [tempo,setTempo]=useState(56);const [sequence,setSequence]=useState<TwinSequenceStep[]>(baseSequence);const [playing,setPlaying]=useState(false);const [activeStep,setActiveStep]=useState(0);const [script,setScript]=useState("Bonjour, bienvenue sur Whappy. Aujourd’hui je vous présente une opportunité pensée pour vous. Regardez ce produit : il est disponible maintenant et je peux répondre à vos questions.");const [language,setLanguage]=useState("fr-FR");const [busy,setBusy]=useState(false);const [recording,setRecording]=useState<"voice"|"movement"|null>(null);const [recordSeconds,setRecordSeconds]=useState(0);const [previewUrl,setPreviewUrl]=useState("");
  const streamRef=useRef<MediaStream|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const chunksRef=useRef<Blob[]>([]);const startedRef=useRef(0);const videoRef=useRef<HTMLVideoElement>(null);const timersRef=useRef<number[]>([]);const notifyRef=useRef(notify);
  useEffect(()=>{notifyRef.current=notify;},[notify]);
  useEffect(()=>watchTwinProfile(userId,setProfile,()=>notifyRef.current("Profil du Double momentanément hors ligne")),[userId]);
  useEffect(()=>watchTwinAutomations(userId,setAutomations,()=>notifyRef.current("Automatisations momentanément hors ligne")),[userId]);
  useEffect(()=>{if(!recording)return;const timer=window.setInterval(()=>setRecordSeconds(Math.floor((Date.now()-startedRef.current)/1000)),500);return()=>window.clearInterval(timer);},[recording]);
  useEffect(()=>()=>{streamRef.current?.getTracks().forEach((track)=>track.stop());timersRef.current.forEach(window.clearTimeout);if(previewUrl)URL.revokeObjectURL(previewUrl);window.speechSynthesis?.cancel();},[previewUrl]);
  const initials=useMemo(()=>userName.split(/\s+/).map((part)=>part[0]).join("").slice(0,2).toUpperCase()||"WH",[userName]);
  const totalDuration=sequence.reduce((sum,item)=>sum+item.duration,0);
  const readiness=[consent,Boolean(profile?.videoUrl),Boolean(profile?.voiceUrl),Boolean(profile?.movementUrl),automations.length>0].filter(Boolean).length;

  function clearTimers(){timersRef.current.forEach(window.clearTimeout);timersRef.current=[];}
  function runSequence(){if(!consent){notify("Validez d’abord l’utilisation de votre propre identité");setTab("capture");return;}clearTimers();setPlaying(true);let elapsed=0;sequence.forEach((item,index)=>{timersRef.current.push(window.setTimeout(()=>{setActiveStep(index);setGesture(item.gesture);},elapsed*1000));elapsed+=Math.max(1,item.duration);});timersRef.current.push(window.setTimeout(()=>{setPlaying(false);setGesture("neutral");},elapsed*1000));}
  function speak(){if(!("speechSynthesis" in window)){notify("La synthèse vocale de prévisualisation n’est pas disponible ici");return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(script);utterance.lang=language;utterance.rate=.75+tempo/100;utterance.pitch=.9+intensity/250;utterance.onstart=()=>{setPlaying(true);runSequence();};utterance.onend=()=>setPlaying(false);window.speechSynthesis.speak(utterance);notify(profile?.voiceUrl?"Aperçu avec une voix système — votre empreinte est conservée pour le moteur neuronal":"Aperçu avec une voix système. Enregistrez votre voix pour préparer son clonage.");}
  async function persistConsent(value:boolean){setConsent(value);try{await saveTwinProfile(userId,{displayName:userName,identityConsent:value,voiceConsent:value,movementConsent:value,voiceStatus:profile?.voiceStatus||"empty",movementStatus:profile?.movementStatus||"empty"});notify(value?"Consentement du Double enregistré":"Autorisations du Double révoquées");}catch{notify("Le consentement n’a pas pu être synchronisé");}}
  async function startCapture(kind:"voice"|"movement"){
    if(!consent){notify("Confirmez d’abord que l’image et la voix sont les vôtres");return;}if(typeof MediaRecorder==="undefined"){notify("Ce navigateur ne prend pas en charge l’enregistrement");return;}
    await saveTwinProfile(userId,{displayName:userName,identityConsent:true,voiceConsent:true,movementConsent:true,voiceStatus:profile?.voiceStatus||"empty",movementStatus:profile?.movementStatus||"empty"}).catch(()=>undefined);
    try{const stream=await navigator.mediaDevices.getUserMedia(kind==="voice"?{audio:{echoCancellation:true,noiseSuppression:true}}:{audio:true,video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}}});streamRef.current=stream;if(kind==="movement"&&videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}const preferred=kind==="voice"?(MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm"):(MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm");const recorder=new MediaRecorder(stream,{mimeType:preferred});recorderRef.current=recorder;chunksRef.current=[];startedRef.current=Date.now();setRecordSeconds(0);setRecording(kind);recorder.ondataavailable=(event)=>event.data.size&&chunksRef.current.push(event.data);recorder.onstop=async()=>{const blob=new Blob(chunksRef.current,{type:preferred});const file=new File([blob],`${kind}-${Date.now()}.webm`,{type:preferred});stream.getTracks().forEach((track)=>track.stop());setRecording(null);if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl(URL.createObjectURL(blob));setBusy(true);try{await uploadTwinAsset(userId,file,kind);notify(kind==="voice"?"Empreinte vocale sécurisée et prête à entraîner":"Capsule de mouvements analysable enregistrée");}catch(error){notify(error instanceof Error&&error.message==="asset-too-large"?"La capture dépasse la taille autorisée":"La capture n’a pas été synchronisée");}finally{setBusy(false);}};recorder.start(400);}catch{notify(`Autorisez ${kind==="voice"?"le microphone":"la caméra et le microphone"} pour continuer`);}}
  function stopCapture(){if(recorderRef.current?.state==="recording")recorderRef.current.stop();}
  function addGesture(item:TwinGesture){const found=gestures.find((candidate)=>candidate.id===item);setSequence((current)=>[...current,{gesture:item,duration:3,label:found?.label||"Mouvement"}]);}
  async function addAutomation(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{await createTwinAutomation(userId,{name:String(form.get("name")||"Automatisation Double"),trigger:String(form.get("trigger")||"new-listing"),channel:String(form.get("channel")||"market"),action:String(form.get("action")||"prepare-video"),script:String(form.get("script")||script).slice(0,4000),enabled:true});notify("Automatisation du Double activée");event.currentTarget.reset();}catch{notify("L’automatisation n’a pas été créée");}finally{setBusy(false);}}
  async function prepareRender(){if(!consent){notify("Le consentement est obligatoire avant toute production");return;}setBusy(true);try{await createTwinRenderJob(userId,{title:"Séquence commerciale Whappy",script,language,voiceMode:profile?.voiceUrl?"owner-voice-sample":"system-preview",sequence});notify("Plan de production enregistré. Le rendu neuronal sera lancé après connexion du moteur vidéo.");}catch{notify("Le plan de production n’a pas été enregistré");}finally{setBusy(false);}}

  return <div className="twin-engine"><header className="twin-engine-hero"><div><span><i/> WHAPPY DOUBLE ENGINE / VOTRE IDENTITÉ</span><h2>Donnez une présence<br/><em>vivante</em> à votre Double.</h2><p>Composez ses mouvements, enregistrez votre voix, écrivez son scénario et automatisez ses interventions commerciales — sous votre contrôle permanent.</p><div><b>✓ Votre image uniquement</b><b>✓ Voix révocable</b><b>✓ Label IA permanent</b></div></div><aside><small>NIVEAU DE PRÉPARATION</small><strong>{readiness*20}%</strong><div><i style={{width:`${readiness*20}%`}}/></div><p>{readiness<5?"Complétez les modules pour rendre le Double autonome.":"Moteur préparé pour la production."}</p></aside></header>
    <nav className="twin-engine-tabs">{([['engine','Moteur mouvement','⌁'],['capture','Identité vidéo','▣'],['voice','Clone vocal','◖'],['automation','Automatiser','⌘'],['produce','Produire','✦']] as [Tab,string,string][]).map(([id,label,icon])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}><span>{icon}</span>{label}{id==="voice"&&profile?.voiceUrl&&<i/>}</button>)}</nav>
    {tab==="engine"&&<section className="motion-lab"><div className="motion-stage"><div className={`motion-avatar ${gesture} ${playing?"playing":""}`} style={{'--motion-intensity':intensity/100,'--motion-tempo':`${1.45-tempo/100}s`} as React.CSSProperties}><div className="motion-aura"/><div className="avatar-head"><span>{initials}</span><i/><i/></div><div className="avatar-body"><span className="arm left"/><span className="torso"><b>IA</b></span><span className="arm right"/><span className="leg left"/><span className="leg right"/></div><small>DOUBLE DE {userName.toUpperCase()}</small></div><div className="motion-hud"><span>GESTE ACTIF</span><strong>{gestures.find((item)=>item.id===gesture)?.label}</strong><i>{playing?"MOUVEMENT EN COURS":"PRÊT"}</i></div><div className="motion-floor"/></div><aside className="motion-controls"><header><div><small>MOTION CORE 1.0</small><h3>Bibliothèque de mouvements</h3></div><button onClick={runSequence}>▶ Séquence</button></header><div className="gesture-grid">{gestures.map((item)=><button className={gesture===item.id?"active":""} onClick={()=>setGesture(item.id)} key={item.id}><span>{item.icon}</span><div><strong>{item.label}</strong><small>{item.description}</small></div><b onClick={(event)=>{event.stopPropagation();addGesture(item.id)}}>＋</b></button>)}</div><div className="motion-sliders"><label>Énergie <b>{intensity}%</b><input type="range" min="20" max="100" value={intensity} onChange={(event)=>setIntensity(Number(event.target.value))}/></label><label>Rythme <b>{tempo}%</b><input type="range" min="20" max="100" value={tempo} onChange={(event)=>setTempo(Number(event.target.value))}/></label></div></aside></section>}
    {tab==="capture"&&<section className="twin-module capture-module"><div className="module-copy"><span>01 / IDENTITÉ SOUVERAINE</span><h3>Apprenez-lui votre présence.</h3><p>Une capsule de mouvements permet de préparer votre signature corporelle : posture, rythme des mains, regard et déplacement. Aucun visage tiers n’est autorisé.</p><label className="sovereign-consent"><input type="checkbox" checked={consent} onChange={(event)=>void persistConsent(event.target.checked)}/><span><strong>Je suis la personne enregistrée</strong><small>J’autorise Whappy à préparer mon Double avec ma propre image, ma propre voix et mes mouvements. Je peux tout révoquer.</small></span></label><div className="capture-guide"><b>1</b><span>Face caméra, corps visible</span><b>2</b><span>Saluez puis présentez un objet</span><b>3</b><span>Marchez d’un pas sur le côté</span></div></div><div className={`capture-stage ${recording||""}`}><video ref={videoRef} muted playsInline/>{!recording&&<div><span>⌁</span><strong>{profile?.movementUrl?"Signature mouvement enregistrée":"Caméra prête pour Motion Capture"}</strong><small>Durée recommandée : 30 à 60 secondes</small></div>}{recording==="movement"&&<b>● CAPTURE · {clock(recordSeconds)}</b>}<button disabled={busy} onClick={recording==="movement"?stopCapture:()=>startCapture("movement")}>{recording==="movement"?"■ Terminer la capture":"▣ Capturer mes mouvements"}</button></div></section>}
    {tab==="voice"&&<section className="twin-module voice-module"><div className="voice-orb"><div className={recording==="voice"?"listening":""}>{Array.from({length:36},(_,index)=><i style={{'--i':index} as React.CSSProperties} key={index}/>)}</div><span>{recording==="voice"?clock(recordSeconds):profile?.voiceUrl?"✓":"◖"}</span></div><div className="module-copy"><span>02 / VOICE DNA</span><h3>Votre voix. Votre rythme. Votre autorisation.</h3><p>Lisez un échantillon clair. Whappy conserve l’empreinte pour le futur moteur neuronal ; l’aperçu actuel utilise une voix système et ne prétend pas encore reproduire votre timbre.</p><blockquote>« Bonjour, je suis {userName}. Cette voix est la mienne et j’autorise son utilisation uniquement par mon Double Whappy pour les contenus que je valide. »</blockquote><button className={recording==="voice"?"stop":""} disabled={busy} onClick={recording==="voice"?stopCapture:()=>startCapture("voice")}>{recording==="voice"?"■ Terminer et sécuriser":profile?.voiceUrl?"↻ Réenregistrer ma voix":"● Enregistrer mon empreinte vocale"}</button>{previewUrl&&<audio src={previewUrl} controls/>}<small className="voice-safety">◆ Une révocation désactive les productions futures. Les contenus générés restent identifiés comme IA.</small></div></section>}
    {tab==="automation"&&<section className="automation-lab"><form onSubmit={addAutomation}><span>03 / ORCHESTRATEUR</span><h3>Créez un Double qui agit au bon moment.</h3><div className="auto-grid"><label>Nom<input name="name" required placeholder="Ex. Présenter chaque nouvelle annonce"/></label><label>Déclencheur<select name="trigger"><option value="new-listing">Nouvelle annonce publiée</option><option value="incoming-message">Question client reçue</option><option value="live-start">Démarrage d’un direct</option><option value="schedule">Horaire programmé</option><option value="cart-abandoned">Panier abandonné</option></select></label><label>Destination<select name="channel"><option value="market">Marketplace</option><option value="inbox">Message privé</option><option value="live">Direct Whappy</option><option value="moments">Fil Moments</option></select></label><label>Action<select name="action"><option value="prepare-video">Préparer une vidéo</option><option value="reply-video">Préparer une réponse vidéo</option><option value="publish-moment">Créer un Moment</option><option value="notify-owner">Demander ma validation</option></select></label></div><label>Script de base<textarea name="script" defaultValue={script}/></label><button disabled={busy||!consent}>＋ Activer cette automatisation</button><small>Les publications externes nécessitent toujours votre validation tant que le moteur de rendu n’est pas connecté.</small></form><div className="automation-list"><header><small>RÈGLES ACTIVES</small><strong>{automations.filter((item)=>item.enabled).length} automatisation(s)</strong></header>{automations.map((item)=><article key={item.id}><span className={item.enabled?"on":""}>⌘</span><div><strong>{item.name}</strong><small>{item.trigger} → {item.channel}</small></div><button onClick={()=>void toggleTwinAutomation(userId,item.id,!item.enabled)}>{item.enabled?"Actif":"Pause"}</button><button className="danger" onClick={()=>void removeTwinAutomation(userId,item.id)}>×</button></article>)}{!automations.length&&<p>Aucune règle. Créez la première automatisation de votre Double.</p>}</div></section>}
    {tab==="produce"&&<section className="production-lab"><div className="production-script"><span>04 / DIRECTOR</span><h3>Écrivez. Chorégraphiez. Lancez.</h3><label>Langue<select value={language} onChange={(event)=>setLanguage(event.target.value)}><option value="fr-FR">Français</option><option value="ln-CD">Lingala</option><option value="en-US">Anglais</option></select></label><label>Scénario<textarea value={script} onChange={(event)=>setScript(event.target.value)} maxLength={4000}/></label><div><button onClick={speak}>▶ Prévisualiser voix + mouvements</button><button className="primary" disabled={busy||!consent} onClick={prepareRender}>✦ Préparer la production</button></div><small>Aperçu immédiat avec la voix du système. Le rendu photoréaliste et le clonage neuronal nécessitent la connexion d’un fournisseur vidéo/voix.</small></div><div className="sequence-board"><header><div><small>TIMELINE MOUVEMENT</small><strong>{totalDuration} secondes · {sequence.length} gestes</strong></div><button onClick={()=>setSequence(baseSequence)}>Réinitialiser</button></header><div className="sequence-track">{sequence.map((item,index)=><button className={playing&&activeStep===index?"active":""} style={{flex:item.duration}} key={`${item.label}-${index}`} onClick={()=>{setGesture(item.gesture);setActiveStep(index)}}><span>{gestures.find((candidate)=>candidate.id===item.gesture)?.icon}</span><strong>{item.label}</strong><small>{item.duration}s</small><i onClick={(event)=>{event.stopPropagation();setSequence((current)=>current.filter((_,itemIndex)=>itemIndex!==index))}}>×</i></button>)}</div><div className="sequence-library">{gestures.slice(1).map((item)=><button onClick={()=>addGesture(item.id)} key={item.id}>＋ {item.label}</button>)}</div><footer><span>DIVULGATION AUTOMATIQUE</span><strong>Créé avec le Double IA de {userName}</strong><i>✓ Activée</i></footer></div></section>}
  </div>;
}
